version: '3'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/etc/cert:/etc/nginx/cert
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true

  srs:
    image: ossrs/srs:4
    command: ./objs/srs -c rtmp2rtc.conf
    environment:
      - CANDIDATE=192.168.1.4
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
      - "1990:1990"
      - "8088:8088"
      - "8000:8000/udp"
      